### ISSUE TITLE
A couple of issues with execStreaming long running tasks

### ISSUE THREAD

**Issue by eastlondoner** [cloudflare/sandbox-sdk#101]
Below is an adaptation of the code I have ended up using with execStreaming. It addresses a few issues that would be great for sandbox sdk to improve

1) you have to keep bumping the container activity timeout otherwise cloudflare shuts down the container while your process is still running
2) the execStream response just “hangs” in a bunch of cases. For example if the container crashes or if bun closes the connection because it’s idle - there’s no error on the execStream. So it’s not safe to consume it normally, instead we regularly check on the health of the sandbox and we consume the stream by calling next with a timeout race so we can detect and handle failure

```
  // Run the exec command in streaming mode
      const commandExec = input.command;
      const resultStream = await execStreamOnSandbox(sandbox, sandboxSession.id, commandExec, {
        timeout: 30 * 60 * 1000, // 30 minutes total timeout - that should be enough
      });
      let stdout = "";
      let stderr = "";
      const stream = resultStream[Symbol.asyncIterator]();

      // we have to keep an eye on the sandbox, sometimes it crashes and we don't get an error from the stream
      let sandboxHealthy = true;
      const interval = setInterval(async () => {
        try {
          const state = await sandbox.getState();
          if (state.status !== "healthy") {
            sandboxHealthy = false;
          }
          await sandbox.renewActivityTimeout();
        } catch (err) {
          logger.error("Error renewing activity timeout", err);
        }
      }, 5000);

      // try finally block to close the interval
      try {
        while (true) {
          if (!sandboxHealthy) {
            logger.warn("Sandbox is not healthy, exiting");
            return {
              success: false,
              message: "Sandbox crashed after completing this work",
              stdout,
              stderr,
              exitCode: 1,
            };
          }

          // We allow 260 seconds for the next stream event, if we don't get one, we timeout
          // this is because the Bun Server idle timeout is 255 seconds and if we don't get
          // an event we probably will never get one but we don't get an error either from
          // sandbox sdk when bun closes the connection
          const abortController = new AbortController();
          const getNextStreamEventTimeout = setTimeoutPromise(260_000, {
            signal: abortController.signal,
          }).then(() => "TIMEOUT" as const);

          const result = await Promise.race([stream.next(), getNextStreamEventTimeout]);

          // Clean up the timeout regardless of which promise won the race
          abortController.abort();

          if (result === "TIMEOUT") {
            return {
              message: "The connection to the sandbox timed out",
              success: false,
              stdout,
              stderr,
              exitCode: 1,
            };
          }
          if (result.done) {
            logger.info("Exec readable exhausted without complete event", {
              input,
              stdout,
              stderr,
            });
            // should not get here
            return {
              success: false,
              message: "Result stream terminated before process completion signal was received",
              stdout,
              stderr,
              exitCode: 1,
            };
          }
          const event = result.value;
          switch (event.type) {
            case "stdout":
              stdout += event.data;
              logger.info(`Exec stdout: ${event.data}`);
              break;
            case "stderr":
              stderr += event.data;
              logger.info(`Exec stderr: ${event.data}`);
              break;
            case "error":
              stderr += event.data;
              logger.info(`Exec error: ${event.data}`);
              logger.error(`Error running \`${commandExec}\` in sandbox`, event);
              return {
                message: "Execution errors occurred",
                success: false,
                stdout,
                stderr,
                exitCode: 1,
              };
            case "complete":
              logger.log(`Tests ${event.exitCode === 0 ? "passed" : "failed"}`);
              return {
                message:
                  event.exitCode === 0
                    ? "Execution completed successfully"
                    : "Execution completed with errors",
                success: event.exitCode === 0,
                stdout,
                stderr,
                exitCode: event.exitCode,
              };
          }
        }
      } finally {
        clearInterval(interval);
      }
    };
```

**Comment by whoiskatrin** [comment]
@eastlondoner can you check if this is still happening in the latest version?

**Comment by whoiskatrin** [comment]
could you please try it with 
`npm i https://pkg.pr.new/cloudflare/sandbox-sdk/@cloudflare/sandbox@137`
commit: [b3afdc7](https://github.com/cloudflare/sandbox-sdk/runs/53492903893)

```
🐳 Docker Image Published
FROM cloudflare/sandbox:0.0.0-pr-137-2a17b4e
Version: 0.0.0-pr-137-2a17b4e
```

**Comment by jplhomer** [comment]
@whoiskatrin Gave this a shot but can't seem to get any `exec` or `execStream` calls to work due to a cryptic `SandboxError`:

```
{"level":"info","msg":"Repository cloned completed successfully","component":"sandbox-do","sandboxId":"e4a26287faf99cdd230676a20657f2af67defbf05796b9ebbe92c4deb5b978d4","traceId":"tr_a2a41f71857a4153","details":"https://github.com/cloudflare/agents (branch: main) -> agents","timestamp":"2025-10-25T13:43:30.648Z"}
✘ [ERROR] Uncaught SandboxError Error

      at createErrorFromResponse
  (file:///Users/joshlarson/src/tries/2025-10-15-cf-sandbox/node_modules/@cloudflare/sandbox/src/errors/adapter.ts:178:14)
      at handleErrorResponse
  (file:///Users/joshlarson/src/tries/2025-10-15-cf-sandbox/node_modules/@cloudflare/sandbox/src/clients/base-client.ts:177:19)


[wrangler:error] Error: SandboxError
    at async Object.fetch (file:///Users/joshlarson/src/tries/2025-10-15-cf-sandbox/src/index.ts:21:20)
    at async jsonError (file:///Users/joshlarson/src/tries/2025-10-15-cf-sandbox/node_modules/wrangler/templates/middleware/middleware-miniflare3-json-error.ts:22:10)
    at async drainBody (file:///Users/joshlarson/src/tries/2025-10-15-cf-sandbox/node_modules/wrangler/templates/middleware/middleware-ensure-req-body-drained.ts:5:10)
```

I'm probably doing something silly though!

**Comment by whoiskatrin** [comment]
> @whoiskatrin Gave this a shot but can't seem to get any `exec` or `execStream` calls to work due to a cryptic `SandboxError`:
> 
> ```
> {"level":"info","msg":"Repository cloned completed successfully","component":"sandbox-do","sandboxId":"e4a26287faf99cdd230676a20657f2af67defbf05796b9ebbe92c4deb5b978d4","traceId":"tr_a2a41f71857a4153","details":"https://github.com/cloudflare/agents (branch: main) -> agents","timestamp":"2025-10-25T13:43:30.648Z"}
> ✘ [ERROR] Uncaught SandboxError Error
> 
>       at createErrorFromResponse
>   (file:///Users/joshlarson/src/tries/2025-10-15-cf-sandbox/node_modules/@cloudflare/sandbox/src/errors/adapter.ts:178:14)
>       at handleErrorResponse
>   (file:///Users/joshlarson/src/tries/2025-10-15-cf-sandbox/node_modules/@cloudflare/sandbox/src/clients/base-client.ts:177:19)
> 
> 
> [wrangler:error] Error: SandboxError
>     at async Object.fetch (file:///Users/joshlarson/src/tries/2025-10-15-cf-sandbox/src/index.ts:21:20)
>     at async jsonError (file:///Users/joshlarson/src/tries/2025-10-15-cf-sandbox/node_modules/wrangler/templates/middleware/middleware-miniflare3-json-error.ts:22:10)
>     at async drainBody (file:///Users/joshlarson/src/tries/2025-10-15-cf-sandbox/node_modules/wrangler/templates/middleware/middleware-ensure-req-body-drained.ts:5:10)
> ```
> 
> I'm probably doing something silly though!

Need to dig into this!

**Comment by eastlondoner** [comment]
I was able to get this to work with the latest docker image and some janky code I threw in to handle parsing the raw SSE event stream bytes that were returned.

But when I gave it a long running task it threw RPC disconnected while consuming readable stream errors. I think it’s safer with Cloudflare to return a response to the caller than sending them a readable stream. But tricky to make a nice interface for that

**Comment by whoiskatrin** [comment]
@eastlondoner will pick this up soon

**Comment by whoiskatrin** [comment]
@eastlondoner this should be solved now, please use keepAlive flag + destroy (), see the docs update: https://developers.cloudflare.com/sandbox/configuration/sandbox-options/#keepalive

**Comment by rishabhparikh** [comment]
The `keepAlive` flag doesn't seem to be respected when I test locally with `npx wrangler dev`. I have not tested this on a production deploy.

My sandbox is still receiving a SIGTERM message after 10 mins. 

I'm using package and image versions 0.4.11.

Worker code:
```index.ts
const sandbox = getSandbox(env.Sandbox, sessionId, {
  keepAlive: true,
});

// Kicks off a long-running process
await sandbox.execStream(
    `bun run index.ts ${JSON.stringify(inputPrompt)}`
);
```

Sandbox Dockerfile:
```Dockerfile
FROM docker.io/cloudflare/sandbox:0.4.11
```

Worker's package.json:
```json
{
  "name": "@cloudflare/sandbox-minimal-example",
  "version": "1.0.0",
  "type": "module",
  "private": true,
  "description": "A minimal example of using the Sandbox SDK",
  "scripts": {
    "deploy": "wrangler deploy",
    "dev": "wrangler dev",
    "start": "wrangler dev",
    "cf-typegen": "wrangler types"
  },
  "devDependencies": {
    "@types/node": "^24.1.0",
    "typescript": "^5.8.3",
    "wrangler": "^4.43.0"
  },
  "author": "",
  "license": "MIT",
  "dependencies": {
    "@cloudflare/sandbox": "^0.4.11"
  }
}

```

**Comment by whoiskatrin** [comment]
@rishabhparikh yes, I think it is because of DO hibernation cycles. Do you mind giving this a test? https://github.com/cloudflare/sandbox-sdk/pull/164 

This should resolve it.

**Comment by whoiskatrin** [comment]
> The `keepAlive` flag doesn't seem to be respected when I test locally with `npx wrangler dev`. I have not tested this on a production deploy.
> 
> My sandbox is still receiving a SIGTERM message after 10 mins.
> 
> I'm using package and image versions 0.4.11.
> 
> Worker code:
> 
> const sandbox = getSandbox(env.Sandbox, sessionId, {
>   keepAlive: true,
> });
> 
> // Kicks off a long-running process
> await sandbox.execStream(
>     `bun run index.ts ${JSON.stringify(inputPrompt)}`
> );
> Sandbox Dockerfile:
> 
> FROM docker.io/cloudflare/sandbox:0.4.11
> Worker's package.json:
> 
> {
>   "name": "@cloudflare/sandbox-minimal-example",
>   "version": "1.0.0",
>   "type": "module",
>   "private": true,
>   "description": "A minimal example of using the Sandbox SDK",
>   "scripts": {
>     "deploy": "wrangler deploy",
>     "dev": "wrangler dev",
>     "start": "wrangler dev",
>     "cf-typegen": "wrangler types"
>   },
>   "devDependencies": {
>     "@types/node": "^24.1.0",
>     "typescript": "^5.8.3",
>     "wrangler": "^4.43.0"
>   },
>   "author": "",
>   "license": "MIT",
>   "dependencies": {
>     "@cloudflare/sandbox": "^0.4.11"
>   }
> }

Actually, looking at it now, it seems like the release for 0.4.12 has failed and keepAlive was never released actually. Let me get this out now and it should work normally in 0.4.12 for you

**Comment by rishabhparikh** [comment]
That makes sense, as I didn't see the callsites you referenced in 0.4.11. Thanks for publishing the newest version. I'll give it a test today.

**Comment by rishabhparikh** [comment]
Appears to be working as intended now.
